version: "3.7"
services:
  api:
    build:
      context: ./vizir-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
  client:
    build:
      context: ./vizir-client
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - "3000:80"