version: "3.7"
services:
  api:
    build:
      context: ./vizir-api
      dockerfile: dev.Dockerfile
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - ./vizir-api/src:/usr/src/app/src
